//
// SnowingView.swift
// Rooms!
//
// Animation created by Alan Guilfoyle on 12/02/15
// Code generated by Core Animator version 1.2.4 on 12/02/15.
//


import UIKit

@IBDesignable
class SnowingView : UIView {


	var animationCompletions = Dictionary<CAAnimation, (Bool) -> Void>()
	var viewsByName: [String : UIView]!

	// - MARK: Life Cycle

	convenience init() {
		self.init(frame: CGRect(x: 0, y: 0, width: 520, height: 520))
	}

	override init(frame: CGRect) {
		super.init(frame: frame)
		self.setupHierarchy()
	}

	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		self.setupHierarchy()
	}

	// - MARK: Scaling

	override func layoutSubviews() {
		super.layoutSubviews()

		if let scalingView = self.viewsByName["__scaling__"] {
			var xScale = self.bounds.size.width / scalingView.bounds.size.width
			var yScale = self.bounds.size.height / scalingView.bounds.size.height
			switch contentMode {
			case .ScaleToFill:
				break
			case .ScaleAspectFill:
				let scale = max(xScale, yScale)
				xScale = scale
				yScale = scale
			default:
				let scale = min(xScale, yScale)
				xScale = scale
				yScale = scale
			}
			scalingView.transform = CGAffineTransformMakeScale(xScale, yScale)
			scalingView.center = CGPoint(x:CGRectGetMidX(self.bounds), y:CGRectGetMidY(self.bounds))
		}
	}

	// - MARK: Setup

	func setupHierarchy() {
		var viewsByName: [String : UIView] = [:]
		let bundle = NSBundle(forClass:self.dynamicType)
		let __scaling__ = UIView()
		__scaling__.bounds = CGRect(x:0, y:0, width:520, height:520)
		__scaling__.center = CGPoint(x:260.0, y:260.0)
		__scaling__.layer.masksToBounds = true
		self.addSubview(__scaling__)
		viewsByName["__scaling__"] = __scaling__

		let chill = UIImageView()
		chill.bounds = CGRect(x:0, y:0, width:1024.0, height:502.0)
		var imgChill: UIImage!
		if let imagePath = bundle.pathForResource("chilling.png", ofType:nil) {
			imgChill = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from 'chilling.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		chill.image = imgChill
		chill.contentMode = .Center;
		chill.layer.position = CGPoint(x:260.000, y:445.445)
		chill.alpha = 0.00
		chill.transform = CGAffineTransformMakeScale(0.32, 0.32)
		__scaling__.addSubview(chill)
		viewsByName["chilling"] = chill

		let snowFlake05 = UIImageView()
		snowFlake05.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		var imgSnowing: UIImage!
		if let imagePath = bundle.pathForResource("Snowing.png", ofType:nil) {
			imgSnowing = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from 'Snowing.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		snowFlake05.image = imgSnowing
		snowFlake05.contentMode = .Center;
		snowFlake05.layer.position = CGPoint(x:126.307, y:215.984)
		snowFlake05.alpha = 0.00
		snowFlake05.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake05)
		viewsByName["snowFlake05"] = snowFlake05

		let snowFlake04 = UIImageView()
		snowFlake04.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake04.image = imgSnowing
		snowFlake04.contentMode = .Center;
		snowFlake04.layer.position = CGPoint(x:185.123, y:269.626)
		snowFlake04.alpha = 0.00
		snowFlake04.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake04)
		viewsByName["snowFlake04"] = snowFlake04

		let snowFlake03 = UIImageView()
		snowFlake03.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake03.image = imgSnowing
		snowFlake03.contentMode = .Center;
		snowFlake03.layer.position = CGPoint(x:309.090, y:318.437)
		snowFlake03.alpha = 0.00
		snowFlake03.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake03)
		viewsByName["snowFlake03"] = snowFlake03

		let snowFlake02 = UIImageView()
		snowFlake02.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake02.image = imgSnowing
		snowFlake02.contentMode = .Center;
		snowFlake02.layer.position = CGPoint(x:250.274, y:260.796)
		snowFlake02.alpha = 0.00
		snowFlake02.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake02)
		viewsByName["snowFlake02"] = snowFlake02

		let snowFlake01 = UIImageView()
		snowFlake01.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake01.image = imgSnowing
		snowFlake01.contentMode = .Center;
		snowFlake01.layer.position = CGPoint(x:347.460, y:237.995)
		snowFlake01.alpha = 0.00
		snowFlake01.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake01)
		viewsByName["snowFlake01"] = snowFlake01

		let snowFlake = UIImageView()
		snowFlake.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake.image = imgSnowing
		snowFlake.contentMode = .Center;
		snowFlake.layer.position = CGPoint(x:406.276, y:280.637)
		snowFlake.alpha = 0.00
		snowFlake.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake)
		viewsByName["snowFlake"] = snowFlake

		let snowFlake12 = UIImageView()
		snowFlake12.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake12.image = imgSnowing
		snowFlake12.contentMode = .Center;
		snowFlake12.layer.position = CGPoint(x:406.276, y:280.637)
		snowFlake12.alpha = 0.00
		snowFlake12.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake12)
		viewsByName["snowFlake12"] = snowFlake12

		let snowFlake13 = UIImageView()
		snowFlake13.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake13.image = imgSnowing
		snowFlake13.contentMode = .Center;
		snowFlake13.layer.position = CGPoint(x:347.460, y:237.995)
		snowFlake13.alpha = 0.00
		snowFlake13.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake13)
		viewsByName["snowFlake13"] = snowFlake13

		let snowFlake14 = UIImageView()
		snowFlake14.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake14.image = imgSnowing
		snowFlake14.contentMode = .Center;
		snowFlake14.layer.position = CGPoint(x:250.274, y:260.796)
		snowFlake14.alpha = 0.00
		snowFlake14.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake14)
		viewsByName["snowFlake14"] = snowFlake14

		let snowFlake15 = UIImageView()
		snowFlake15.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake15.image = imgSnowing
		snowFlake15.contentMode = .Center;
		snowFlake15.layer.position = CGPoint(x:309.090, y:318.437)
		snowFlake15.alpha = 0.00
		snowFlake15.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake15)
		viewsByName["snowFlake15"] = snowFlake15

		let snowFlake16 = UIImageView()
		snowFlake16.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake16.image = imgSnowing
		snowFlake16.contentMode = .Center;
		snowFlake16.layer.position = CGPoint(x:185.123, y:269.626)
		snowFlake16.alpha = 0.00
		snowFlake16.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake16)
		viewsByName["snowFlake16"] = snowFlake16

		let snowFlake17 = UIImageView()
		snowFlake17.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake17.image = imgSnowing
		snowFlake17.contentMode = .Center;
		snowFlake17.layer.position = CGPoint(x:126.307, y:215.984)
		snowFlake17.alpha = 0.00
		snowFlake17.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake17)
		viewsByName["snowFlake17"] = snowFlake17

		let snowFlake06 = UIImageView()
		snowFlake06.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake06.image = imgSnowing
		snowFlake06.contentMode = .Center;
		snowFlake06.layer.position = CGPoint(x:406.276, y:280.637)
		snowFlake06.alpha = 0.00
		snowFlake06.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake06)
		viewsByName["snowFlake06"] = snowFlake06

		let snowFlake07 = UIImageView()
		snowFlake07.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake07.image = imgSnowing
		snowFlake07.contentMode = .Center;
		snowFlake07.layer.position = CGPoint(x:347.460, y:237.995)
		snowFlake07.alpha = 0.00
		snowFlake07.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake07)
		viewsByName["snowFlake07"] = snowFlake07

		let snowFlake08 = UIImageView()
		snowFlake08.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake08.image = imgSnowing
		snowFlake08.contentMode = .Center;
		snowFlake08.layer.position = CGPoint(x:250.274, y:260.796)
		snowFlake08.alpha = 0.00
		snowFlake08.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake08)
		viewsByName["snowFlake08"] = snowFlake08

		let snowFlake09 = UIImageView()
		snowFlake09.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake09.image = imgSnowing
		snowFlake09.contentMode = .Center;
		snowFlake09.layer.position = CGPoint(x:309.090, y:318.437)
		snowFlake09.alpha = 0.00
		snowFlake09.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake09)
		viewsByName["snowFlake09"] = snowFlake09

		let snowFlake10 = UIImageView()
		snowFlake10.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake10.image = imgSnowing
		snowFlake10.contentMode = .Center;
		snowFlake10.layer.position = CGPoint(x:185.123, y:269.626)
		snowFlake10.alpha = 0.00
		snowFlake10.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake10)
		viewsByName["snowFlake10"] = snowFlake10

		let snowFlake11 = UIImageView()
		snowFlake11.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		snowFlake11.image = imgSnowing
		snowFlake11.contentMode = .Center;
		snowFlake11.layer.position = CGPoint(x:126.307, y:215.984)
		snowFlake11.alpha = 0.00
		snowFlake11.transform = CGAffineTransformMakeScale(0.15, 0.15)
		__scaling__.addSubview(snowFlake11)
		viewsByName["snowFlake11"] = snowFlake11

		let ampersandSnowFlake = UIImageView()
		ampersandSnowFlake.bounds = CGRect(x:0, y:0, width:371.0, height:358.0)
		var imgAmpersandSnowFlake: UIImage!
		if let imagePath = bundle.pathForResource("Ampersand SnowFlake.png", ofType:nil) {
			imgAmpersandSnowFlake = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from 'Ampersand SnowFlake.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		ampersandSnowFlake.image = imgAmpersandSnowFlake
		ampersandSnowFlake.contentMode = .Center;
		ampersandSnowFlake.layer.position = CGPoint(x:260.000, y:179.000)
		__scaling__.addSubview(ampersandSnowFlake)
		viewsByName["Ampersand SnowFlake"] = ampersandSnowFlake

		self.viewsByName = viewsByName
	}

	// - MARK: Spinning

	func addSpinningAnimation() {
		addSpinningAnimationWithBeginTime(0, fillMode: kCAFillModeBoth, removedOnCompletion: false, completion: nil)
	}

	func addSpinningAnimation(completion: ((Bool) -> Void)?) {
		addSpinningAnimationWithBeginTime(0, fillMode: kCAFillModeBoth, removedOnCompletion: false, completion: completion)
	}

	func addSpinningAnimation(removedOnCompletion removedOnCompletion: Bool) {
		addSpinningAnimationWithBeginTime(0, fillMode: removedOnCompletion ? kCAFillModeRemoved : kCAFillModeBoth, removedOnCompletion: removedOnCompletion, completion: nil)
	}

	func addSpinningAnimation(removedOnCompletion removedOnCompletion: Bool, completion: ((Bool) -> Void)?) {
		addSpinningAnimationWithBeginTime(0, fillMode: removedOnCompletion ? kCAFillModeRemoved : kCAFillModeBoth, removedOnCompletion: removedOnCompletion, completion: completion)
	}

	func addSpinningAnimationWithBeginTime(beginTime: CFTimeInterval, fillMode: String, removedOnCompletion: Bool, completion: ((Bool) -> Void)?) {
		let linearTiming = CAMediaTimingFunction(name: kCAMediaTimingFunctionLinear)
		let instantTiming = CAMediaTimingFunction(name: kCAMediaTimingFunctionDefault)
		let anticOverTiming = CAMediaTimingFunction(controlPoints: 0.42, -0.30, 0.58, 1.30)
		if let complete = completion {
			let representativeAnimation = CABasicAnimation(keyPath: "not.a.real.key")
			representativeAnimation.duration = 3.250
			representativeAnimation.delegate = self
			self.layer.addAnimation(representativeAnimation, forKey: "Spinning")
			self.animationCompletions[layer.animationForKey("Spinning")!] = complete
		}

		let snowFlakeRotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlakeRotationAnimation.duration = 3.250
		snowFlakeRotationAnimation.values = [0.000 as Float, 6.263 as Float, 6.263 as Float, 0.000 as Float, 6.283 as Float]
		snowFlakeRotationAnimation.keyTimes = [0.000 as Float, 0.423 as Float, 0.654 as Float, 0.654 as Float, 1.000 as Float]
		snowFlakeRotationAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming]
		snowFlakeRotationAnimation.beginTime = beginTime
		snowFlakeRotationAnimation.fillMode = fillMode
		snowFlakeRotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake"]?.layer.addAnimation(snowFlakeRotationAnimation, forKey:"Spinning_Rotation")

		let snowFlakeOpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlakeOpacityAnimation.duration = 3.250
		snowFlakeOpacityAnimation.values = [0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlakeOpacityAnimation.keyTimes = [0.000 as Float, 0.115 as Float, 0.654 as Float, 0.654 as Float, 0.731 as Float, 1.000 as Float]
		snowFlakeOpacityAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming, linearTiming]
		snowFlakeOpacityAnimation.beginTime = beginTime
		snowFlakeOpacityAnimation.fillMode = fillMode
		snowFlakeOpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake"]?.layer.addAnimation(snowFlakeOpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlakeTranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlakeTranslationYAnimation.duration = 3.250
		snowFlakeTranslationYAnimation.values = [0.000 as Float, 328.000 as Float, 328.000 as Float, 0.000 as Float, 331.000 as Float]
		snowFlakeTranslationYAnimation.keyTimes = [0.000 as Float, 0.462 as Float, 0.654 as Float, 0.654 as Float, 1.000 as Float]
		snowFlakeTranslationYAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming]
		snowFlakeTranslationYAnimation.beginTime = beginTime
		snowFlakeTranslationYAnimation.fillMode = fillMode
		snowFlakeTranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake"]?.layer.addAnimation(snowFlakeTranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake02RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake02RotationAnimation.duration = 3.250
		snowFlake02RotationAnimation.values = [0.000 as Float, 6.283 as Float, 6.283 as Float, 0.000 as Float, 6.109 as Float]
		snowFlake02RotationAnimation.keyTimes = [0.000 as Float, 0.462 as Float, 0.654 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake02RotationAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming]
		snowFlake02RotationAnimation.beginTime = beginTime
		snowFlake02RotationAnimation.fillMode = fillMode
		snowFlake02RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake02"]?.layer.addAnimation(snowFlake02RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake02OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake02OpacityAnimation.duration = 3.250
		snowFlake02OpacityAnimation.values = [0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake02OpacityAnimation.keyTimes = [0.000 as Float, 0.154 as Float, 0.654 as Float, 0.654 as Float, 0.731 as Float, 1.000 as Float]
		snowFlake02OpacityAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming, linearTiming]
		snowFlake02OpacityAnimation.beginTime = beginTime
		snowFlake02OpacityAnimation.fillMode = fillMode
		snowFlake02OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake02"]?.layer.addAnimation(snowFlake02OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake02TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake02TranslationYAnimation.duration = 3.250
		snowFlake02TranslationYAnimation.values = [0.000 as Float, 328.000 as Float, 328.000 as Float, 0.000 as Float, 331.000 as Float]
		snowFlake02TranslationYAnimation.keyTimes = [0.000 as Float, 0.462 as Float, 0.654 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake02TranslationYAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming]
		snowFlake02TranslationYAnimation.beginTime = beginTime
		snowFlake02TranslationYAnimation.fillMode = fillMode
		snowFlake02TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake02"]?.layer.addAnimation(snowFlake02TranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake06RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake06RotationAnimation.duration = 3.250
		snowFlake06RotationAnimation.values = [0.000 as Float, 0.000 as Float, 5.934 as Float, 5.934 as Float]
		snowFlake06RotationAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake06RotationAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake06RotationAnimation.beginTime = beginTime
		snowFlake06RotationAnimation.fillMode = fillMode
		snowFlake06RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake06"]?.layer.addAnimation(snowFlake06RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake06OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake06OpacityAnimation.duration = 3.250
		snowFlake06OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake06OpacityAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.192 as Float, 0.307 as Float, 1.000 as Float]
		snowFlake06OpacityAnimation.timingFunctions = [instantTiming, instantTiming, linearTiming, linearTiming]
		snowFlake06OpacityAnimation.beginTime = beginTime
		snowFlake06OpacityAnimation.fillMode = fillMode
		snowFlake06OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake06"]?.layer.addAnimation(snowFlake06OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake06TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake06TranslationYAnimation.duration = 3.250
		snowFlake06TranslationYAnimation.values = [0.000 as Float, 0.000 as Float, 332.000 as Float, 332.000 as Float]
		snowFlake06TranslationYAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake06TranslationYAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake06TranslationYAnimation.beginTime = beginTime
		snowFlake06TranslationYAnimation.fillMode = fillMode
		snowFlake06TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake06"]?.layer.addAnimation(snowFlake06TranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake15RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake15RotationAnimation.duration = 3.250
		snowFlake15RotationAnimation.values = [0.000 as Float, 0.000 as Float, 6.458 as Float, 6.458 as Float]
		snowFlake15RotationAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.962 as Float, 1.000 as Float]
		snowFlake15RotationAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake15RotationAnimation.beginTime = beginTime
		snowFlake15RotationAnimation.fillMode = fillMode
		snowFlake15RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake15"]?.layer.addAnimation(snowFlake15RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake15OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake15OpacityAnimation.duration = 3.250
		snowFlake15OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake15OpacityAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.423 as Float, 1.000 as Float]
		snowFlake15OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake15OpacityAnimation.beginTime = beginTime
		snowFlake15OpacityAnimation.fillMode = fillMode
		snowFlake15OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake15"]?.layer.addAnimation(snowFlake15OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake15TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake15TranslationYAnimation.duration = 3.250
		snowFlake15TranslationYAnimation.values = [0.000 as Float, 0.000 as Float, 330.000 as Float, 330.000 as Float]
		snowFlake15TranslationYAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.962 as Float, 1.000 as Float]
		snowFlake15TranslationYAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake15TranslationYAnimation.beginTime = beginTime
		snowFlake15TranslationYAnimation.fillMode = fillMode
		snowFlake15TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake15"]?.layer.addAnimation(snowFlake15TranslationYAnimation, forKey:"Spinning_TranslationY")

		let ampersandSnowFlakeRotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		ampersandSnowFlakeRotationAnimation.duration = 3.250
		ampersandSnowFlakeRotationAnimation.values = [0.000 as Float, 6.283 as Float, 12.566 as Float, 12.566 as Float]
		ampersandSnowFlakeRotationAnimation.keyTimes = [0.000 as Float, 0.462 as Float, 0.923 as Float, 1.000 as Float]
		ampersandSnowFlakeRotationAnimation.timingFunctions = [anticOverTiming, anticOverTiming, linearTiming]
		ampersandSnowFlakeRotationAnimation.beginTime = beginTime
		ampersandSnowFlakeRotationAnimation.fillMode = fillMode
		ampersandSnowFlakeRotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["Ampersand SnowFlake"]?.layer.addAnimation(ampersandSnowFlakeRotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake10RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake10RotationAnimation.duration = 3.250
		snowFlake10RotationAnimation.values = [0.000 as Float, 0.000 as Float, 5.934 as Float, 5.934 as Float]
		snowFlake10RotationAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake10RotationAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake10RotationAnimation.beginTime = beginTime
		snowFlake10RotationAnimation.fillMode = fillMode
		snowFlake10RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake10"]?.layer.addAnimation(snowFlake10RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake10OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake10OpacityAnimation.duration = 3.250
		snowFlake10OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake10OpacityAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.192 as Float, 0.307 as Float, 1.000 as Float]
		snowFlake10OpacityAnimation.timingFunctions = [instantTiming, instantTiming, linearTiming, linearTiming]
		snowFlake10OpacityAnimation.beginTime = beginTime
		snowFlake10OpacityAnimation.fillMode = fillMode
		snowFlake10OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake10"]?.layer.addAnimation(snowFlake10OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake10TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake10TranslationYAnimation.duration = 3.250
		snowFlake10TranslationYAnimation.values = [0.000 as Float, 0.000 as Float, 332.000 as Float, 332.000 as Float]
		snowFlake10TranslationYAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake10TranslationYAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake10TranslationYAnimation.beginTime = beginTime
		snowFlake10TranslationYAnimation.fillMode = fillMode
		snowFlake10TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake10"]?.layer.addAnimation(snowFlake10TranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake08RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake08RotationAnimation.duration = 3.250
		snowFlake08RotationAnimation.values = [0.000 as Float, 0.000 as Float, 6.109 as Float, 6.109 as Float]
		snowFlake08RotationAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake08RotationAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake08RotationAnimation.beginTime = beginTime
		snowFlake08RotationAnimation.fillMode = fillMode
		snowFlake08RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake08"]?.layer.addAnimation(snowFlake08RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake08OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake08OpacityAnimation.duration = 3.250
		snowFlake08OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake08OpacityAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.192 as Float, 0.307 as Float, 1.000 as Float]
		snowFlake08OpacityAnimation.timingFunctions = [instantTiming, instantTiming, linearTiming, linearTiming]
		snowFlake08OpacityAnimation.beginTime = beginTime
		snowFlake08OpacityAnimation.fillMode = fillMode
		snowFlake08OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake08"]?.layer.addAnimation(snowFlake08OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake08TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake08TranslationYAnimation.duration = 3.250
		snowFlake08TranslationYAnimation.values = [0.000 as Float, 0.000 as Float, 332.000 as Float, 332.000 as Float]
		snowFlake08TranslationYAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake08TranslationYAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake08TranslationYAnimation.beginTime = beginTime
		snowFlake08TranslationYAnimation.fillMode = fillMode
		snowFlake08TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake08"]?.layer.addAnimation(snowFlake08TranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake03RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake03RotationAnimation.duration = 3.250
		snowFlake03RotationAnimation.values = [0.000 as Float, 6.283 as Float, 6.283 as Float, 0.000 as Float, 5.934 as Float]
		snowFlake03RotationAnimation.keyTimes = [0.000 as Float, 0.423 as Float, 0.654 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake03RotationAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming]
		snowFlake03RotationAnimation.beginTime = beginTime
		snowFlake03RotationAnimation.fillMode = fillMode
		snowFlake03RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake03"]?.layer.addAnimation(snowFlake03RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake03OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake03OpacityAnimation.duration = 3.250
		snowFlake03OpacityAnimation.values = [0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake03OpacityAnimation.keyTimes = [0.000 as Float, 0.115 as Float, 0.654 as Float, 0.654 as Float, 0.731 as Float, 1.000 as Float]
		snowFlake03OpacityAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming, linearTiming]
		snowFlake03OpacityAnimation.beginTime = beginTime
		snowFlake03OpacityAnimation.fillMode = fillMode
		snowFlake03OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake03"]?.layer.addAnimation(snowFlake03OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake03TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake03TranslationYAnimation.duration = 3.250
		snowFlake03TranslationYAnimation.values = [0.000 as Float, 328.000 as Float, 328.000 as Float, 0.000 as Float, 331.000 as Float]
		snowFlake03TranslationYAnimation.keyTimes = [0.000 as Float, 0.462 as Float, 0.654 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake03TranslationYAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming]
		snowFlake03TranslationYAnimation.beginTime = beginTime
		snowFlake03TranslationYAnimation.fillMode = fillMode
		snowFlake03TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake03"]?.layer.addAnimation(snowFlake03TranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake09RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake09RotationAnimation.duration = 3.250
		snowFlake09RotationAnimation.values = [0.000 as Float, 0.000 as Float, 6.283 as Float, 6.283 as Float]
		snowFlake09RotationAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake09RotationAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake09RotationAnimation.beginTime = beginTime
		snowFlake09RotationAnimation.fillMode = fillMode
		snowFlake09RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake09"]?.layer.addAnimation(snowFlake09RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake09OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake09OpacityAnimation.duration = 3.250
		snowFlake09OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake09OpacityAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.192 as Float, 0.307 as Float, 1.000 as Float]
		snowFlake09OpacityAnimation.timingFunctions = [instantTiming, instantTiming, linearTiming, linearTiming]
		snowFlake09OpacityAnimation.beginTime = beginTime
		snowFlake09OpacityAnimation.fillMode = fillMode
		snowFlake09OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake09"]?.layer.addAnimation(snowFlake09OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake09TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake09TranslationYAnimation.duration = 3.250
		snowFlake09TranslationYAnimation.values = [0.000 as Float, 0.000 as Float, 332.000 as Float, 332.000 as Float]
		snowFlake09TranslationYAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake09TranslationYAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake09TranslationYAnimation.beginTime = beginTime
		snowFlake09TranslationYAnimation.fillMode = fillMode
		snowFlake09TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake09"]?.layer.addAnimation(snowFlake09TranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake14RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake14RotationAnimation.duration = 3.250
		snowFlake14RotationAnimation.values = [0.000 as Float, 0.000 as Float, 5.760 as Float, 5.760 as Float]
		snowFlake14RotationAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.962 as Float, 1.000 as Float]
		snowFlake14RotationAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake14RotationAnimation.beginTime = beginTime
		snowFlake14RotationAnimation.fillMode = fillMode
		snowFlake14RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake14"]?.layer.addAnimation(snowFlake14RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake14OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake14OpacityAnimation.duration = 3.250
		snowFlake14OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake14OpacityAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.423 as Float, 1.000 as Float]
		snowFlake14OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake14OpacityAnimation.beginTime = beginTime
		snowFlake14OpacityAnimation.fillMode = fillMode
		snowFlake14OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake14"]?.layer.addAnimation(snowFlake14OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake14TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake14TranslationYAnimation.duration = 3.250
		snowFlake14TranslationYAnimation.values = [0.000 as Float, 0.000 as Float, 330.000 as Float, 330.000 as Float]
		snowFlake14TranslationYAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.962 as Float, 1.000 as Float]
		snowFlake14TranslationYAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake14TranslationYAnimation.beginTime = beginTime
		snowFlake14TranslationYAnimation.fillMode = fillMode
		snowFlake14TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake14"]?.layer.addAnimation(snowFlake14TranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake17RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake17RotationAnimation.duration = 3.250
		snowFlake17RotationAnimation.values = [0.000 as Float, 0.000 as Float, 6.283 as Float, 6.283 as Float]
		snowFlake17RotationAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.962 as Float, 1.000 as Float]
		snowFlake17RotationAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake17RotationAnimation.beginTime = beginTime
		snowFlake17RotationAnimation.fillMode = fillMode
		snowFlake17RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake17"]?.layer.addAnimation(snowFlake17RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake17OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake17OpacityAnimation.duration = 3.250
		snowFlake17OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake17OpacityAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.423 as Float, 1.000 as Float]
		snowFlake17OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake17OpacityAnimation.beginTime = beginTime
		snowFlake17OpacityAnimation.fillMode = fillMode
		snowFlake17OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake17"]?.layer.addAnimation(snowFlake17OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake17TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake17TranslationYAnimation.duration = 3.250
		snowFlake17TranslationYAnimation.values = [0.000 as Float, 0.000 as Float, 330.000 as Float, 330.000 as Float]
		snowFlake17TranslationYAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.962 as Float, 1.000 as Float]
		snowFlake17TranslationYAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake17TranslationYAnimation.beginTime = beginTime
		snowFlake17TranslationYAnimation.fillMode = fillMode
		snowFlake17TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake17"]?.layer.addAnimation(snowFlake17TranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake11RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake11RotationAnimation.duration = 3.250
		snowFlake11RotationAnimation.values = [0.000 as Float, 0.000 as Float, 6.109 as Float, 6.109 as Float]
		snowFlake11RotationAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake11RotationAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake11RotationAnimation.beginTime = beginTime
		snowFlake11RotationAnimation.fillMode = fillMode
		snowFlake11RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake11"]?.layer.addAnimation(snowFlake11RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake11OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake11OpacityAnimation.duration = 3.250
		snowFlake11OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake11OpacityAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.192 as Float, 0.307 as Float, 1.000 as Float]
		snowFlake11OpacityAnimation.timingFunctions = [instantTiming, instantTiming, linearTiming, linearTiming]
		snowFlake11OpacityAnimation.beginTime = beginTime
		snowFlake11OpacityAnimation.fillMode = fillMode
		snowFlake11OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake11"]?.layer.addAnimation(snowFlake11OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake11TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake11TranslationYAnimation.duration = 3.250
		snowFlake11TranslationYAnimation.values = [0.000 as Float, 0.000 as Float, 332.000 as Float, 332.000 as Float]
		snowFlake11TranslationYAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake11TranslationYAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake11TranslationYAnimation.beginTime = beginTime
		snowFlake11TranslationYAnimation.fillMode = fillMode
		snowFlake11TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake11"]?.layer.addAnimation(snowFlake11TranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake16RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake16RotationAnimation.duration = 3.250
		snowFlake16RotationAnimation.values = [0.000 as Float, 0.000 as Float, 5.934 as Float, 5.934 as Float]
		snowFlake16RotationAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.962 as Float, 1.000 as Float]
		snowFlake16RotationAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake16RotationAnimation.beginTime = beginTime
		snowFlake16RotationAnimation.fillMode = fillMode
		snowFlake16RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake16"]?.layer.addAnimation(snowFlake16RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake16OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake16OpacityAnimation.duration = 3.250
		snowFlake16OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake16OpacityAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.423 as Float, 1.000 as Float]
		snowFlake16OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake16OpacityAnimation.beginTime = beginTime
		snowFlake16OpacityAnimation.fillMode = fillMode
		snowFlake16OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake16"]?.layer.addAnimation(snowFlake16OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake16TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake16TranslationYAnimation.duration = 3.250
		snowFlake16TranslationYAnimation.values = [0.000 as Float, 0.000 as Float, 330.000 as Float, 330.000 as Float]
		snowFlake16TranslationYAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.962 as Float, 1.000 as Float]
		snowFlake16TranslationYAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake16TranslationYAnimation.beginTime = beginTime
		snowFlake16TranslationYAnimation.fillMode = fillMode
		snowFlake16TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake16"]?.layer.addAnimation(snowFlake16TranslationYAnimation, forKey:"Spinning_TranslationY")

		let chillOpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		chillOpacityAnimation.duration = 3.250
		chillOpacityAnimation.values = [0.000 as Float, 0.000 as Float, 0.000 as Float, 1.000 as Float, 0.303 as Float, 1.000 as Float, 1.000 as Float]
		chillOpacityAnimation.keyTimes = [0.000 as Float, 0.154 as Float, 0.154 as Float, 0.500 as Float, 0.731 as Float, 0.962 as Float, 1.000 as Float]
		chillOpacityAnimation.timingFunctions = [instantTiming, instantTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		chillOpacityAnimation.beginTime = beginTime
		chillOpacityAnimation.fillMode = fillMode
		chillOpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["chilling"]?.layer.addAnimation(chillOpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake07RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake07RotationAnimation.duration = 3.250
		snowFlake07RotationAnimation.values = [0.000 as Float, 0.000 as Float, 6.458 as Float, 6.458 as Float]
		snowFlake07RotationAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake07RotationAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake07RotationAnimation.beginTime = beginTime
		snowFlake07RotationAnimation.fillMode = fillMode
		snowFlake07RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake07"]?.layer.addAnimation(snowFlake07RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake07OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake07OpacityAnimation.duration = 3.250
		snowFlake07OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake07OpacityAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.192 as Float, 0.307 as Float, 1.000 as Float]
		snowFlake07OpacityAnimation.timingFunctions = [instantTiming, instantTiming, linearTiming, linearTiming]
		snowFlake07OpacityAnimation.beginTime = beginTime
		snowFlake07OpacityAnimation.fillMode = fillMode
		snowFlake07OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake07"]?.layer.addAnimation(snowFlake07OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake07TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake07TranslationYAnimation.duration = 3.250
		snowFlake07TranslationYAnimation.values = [0.000 as Float, 0.000 as Float, 332.000 as Float, 332.000 as Float]
		snowFlake07TranslationYAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake07TranslationYAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake07TranslationYAnimation.beginTime = beginTime
		snowFlake07TranslationYAnimation.fillMode = fillMode
		snowFlake07TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake07"]?.layer.addAnimation(snowFlake07TranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake04RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake04RotationAnimation.duration = 3.250
		snowFlake04RotationAnimation.values = [0.000 as Float, 6.283 as Float, 6.283 as Float, 0.000 as Float, 6.458 as Float]
		snowFlake04RotationAnimation.keyTimes = [0.000 as Float, 0.500 as Float, 0.654 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake04RotationAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming]
		snowFlake04RotationAnimation.beginTime = beginTime
		snowFlake04RotationAnimation.fillMode = fillMode
		snowFlake04RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake04"]?.layer.addAnimation(snowFlake04RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake04OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake04OpacityAnimation.duration = 3.250
		snowFlake04OpacityAnimation.values = [0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake04OpacityAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.654 as Float, 0.654 as Float, 0.731 as Float, 1.000 as Float]
		snowFlake04OpacityAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming, linearTiming]
		snowFlake04OpacityAnimation.beginTime = beginTime
		snowFlake04OpacityAnimation.fillMode = fillMode
		snowFlake04OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake04"]?.layer.addAnimation(snowFlake04OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake04TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake04TranslationYAnimation.duration = 3.250
		snowFlake04TranslationYAnimation.values = [0.000 as Float, 328.000 as Float, 328.000 as Float, 0.000 as Float, 331.000 as Float]
		snowFlake04TranslationYAnimation.keyTimes = [0.000 as Float, 0.462 as Float, 0.654 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake04TranslationYAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming]
		snowFlake04TranslationYAnimation.beginTime = beginTime
		snowFlake04TranslationYAnimation.fillMode = fillMode
		snowFlake04TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake04"]?.layer.addAnimation(snowFlake04TranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake05RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake05RotationAnimation.duration = 3.250
		snowFlake05RotationAnimation.values = [0.000 as Float, 6.286 as Float, 6.286 as Float, 0.000 as Float, 6.283 as Float]
		snowFlake05RotationAnimation.keyTimes = [0.000 as Float, 0.462 as Float, 0.654 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake05RotationAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming]
		snowFlake05RotationAnimation.beginTime = beginTime
		snowFlake05RotationAnimation.fillMode = fillMode
		snowFlake05RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake05"]?.layer.addAnimation(snowFlake05RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake05OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake05OpacityAnimation.duration = 3.250
		snowFlake05OpacityAnimation.values = [0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake05OpacityAnimation.keyTimes = [0.000 as Float, 0.154 as Float, 0.654 as Float, 0.654 as Float, 0.731 as Float, 1.000 as Float]
		snowFlake05OpacityAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming, linearTiming]
		snowFlake05OpacityAnimation.beginTime = beginTime
		snowFlake05OpacityAnimation.fillMode = fillMode
		snowFlake05OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake05"]?.layer.addAnimation(snowFlake05OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake05TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake05TranslationYAnimation.duration = 3.250
		snowFlake05TranslationYAnimation.values = [0.000 as Float, 328.000 as Float, 328.000 as Float, 0.000 as Float, 331.000 as Float]
		snowFlake05TranslationYAnimation.keyTimes = [0.000 as Float, 0.462 as Float, 0.654 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake05TranslationYAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming]
		snowFlake05TranslationYAnimation.beginTime = beginTime
		snowFlake05TranslationYAnimation.fillMode = fillMode
		snowFlake05TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake05"]?.layer.addAnimation(snowFlake05TranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake12RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake12RotationAnimation.duration = 3.250
		snowFlake12RotationAnimation.values = [0.000 as Float, 0.000 as Float, 6.109 as Float, 6.109 as Float]
		snowFlake12RotationAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.962 as Float, 1.000 as Float]
		snowFlake12RotationAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake12RotationAnimation.beginTime = beginTime
		snowFlake12RotationAnimation.fillMode = fillMode
		snowFlake12RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake12"]?.layer.addAnimation(snowFlake12RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake12OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake12OpacityAnimation.duration = 3.250
		snowFlake12OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake12OpacityAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.423 as Float, 1.000 as Float]
		snowFlake12OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake12OpacityAnimation.beginTime = beginTime
		snowFlake12OpacityAnimation.fillMode = fillMode
		snowFlake12OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake12"]?.layer.addAnimation(snowFlake12OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake12TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake12TranslationYAnimation.duration = 3.250
		snowFlake12TranslationYAnimation.values = [0.000 as Float, 0.000 as Float, 330.000 as Float, 330.000 as Float]
		snowFlake12TranslationYAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.962 as Float, 1.000 as Float]
		snowFlake12TranslationYAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake12TranslationYAnimation.beginTime = beginTime
		snowFlake12TranslationYAnimation.fillMode = fillMode
		snowFlake12TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake12"]?.layer.addAnimation(snowFlake12TranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake13RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake13RotationAnimation.duration = 3.250
		snowFlake13RotationAnimation.values = [0.000 as Float, 0.000 as Float, 6.283 as Float, 6.283 as Float]
		snowFlake13RotationAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.962 as Float, 1.000 as Float]
		snowFlake13RotationAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake13RotationAnimation.beginTime = beginTime
		snowFlake13RotationAnimation.fillMode = fillMode
		snowFlake13RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake13"]?.layer.addAnimation(snowFlake13RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake13OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake13OpacityAnimation.duration = 3.250
		snowFlake13OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake13OpacityAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.423 as Float, 1.000 as Float]
		snowFlake13OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake13OpacityAnimation.beginTime = beginTime
		snowFlake13OpacityAnimation.fillMode = fillMode
		snowFlake13OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake13"]?.layer.addAnimation(snowFlake13OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake13TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake13TranslationYAnimation.duration = 3.250
		snowFlake13TranslationYAnimation.values = [0.000 as Float, 0.000 as Float, 330.000 as Float, 330.000 as Float]
		snowFlake13TranslationYAnimation.keyTimes = [0.000 as Float, 0.308 as Float, 0.962 as Float, 1.000 as Float]
		snowFlake13TranslationYAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		snowFlake13TranslationYAnimation.beginTime = beginTime
		snowFlake13TranslationYAnimation.fillMode = fillMode
		snowFlake13TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake13"]?.layer.addAnimation(snowFlake13TranslationYAnimation, forKey:"Spinning_TranslationY")

		let snowFlake01RotationAnimation = CAKeyframeAnimation(keyPath: "transform.rotation.z")
		snowFlake01RotationAnimation.duration = 3.250
		snowFlake01RotationAnimation.values = [0.000 as Float, 6.283 as Float, 6.283 as Float, 0.000 as Float, 5.760 as Float]
		snowFlake01RotationAnimation.keyTimes = [0.000 as Float, 0.500 as Float, 0.654 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake01RotationAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming]
		snowFlake01RotationAnimation.beginTime = beginTime
		snowFlake01RotationAnimation.fillMode = fillMode
		snowFlake01RotationAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake01"]?.layer.addAnimation(snowFlake01RotationAnimation, forKey:"Spinning_Rotation")

		let snowFlake01OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		snowFlake01OpacityAnimation.duration = 3.250
		snowFlake01OpacityAnimation.values = [0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		snowFlake01OpacityAnimation.keyTimes = [0.000 as Float, 0.192 as Float, 0.654 as Float, 0.654 as Float, 0.731 as Float, 1.000 as Float]
		snowFlake01OpacityAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming, linearTiming]
		snowFlake01OpacityAnimation.beginTime = beginTime
		snowFlake01OpacityAnimation.fillMode = fillMode
		snowFlake01OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake01"]?.layer.addAnimation(snowFlake01OpacityAnimation, forKey:"Spinning_Opacity")

		let snowFlake01TranslationYAnimation = CAKeyframeAnimation(keyPath: "transform.translation.y")
		snowFlake01TranslationYAnimation.duration = 3.250
		snowFlake01TranslationYAnimation.values = [0.000 as Float, 328.000 as Float, 328.000 as Float, 0.000 as Float, 331.000 as Float]
		snowFlake01TranslationYAnimation.keyTimes = [0.000 as Float, 0.462 as Float, 0.654 as Float, 0.654 as Float, 1.000 as Float]
		snowFlake01TranslationYAnimation.timingFunctions = [linearTiming, instantTiming, instantTiming, linearTiming]
		snowFlake01TranslationYAnimation.beginTime = beginTime
		snowFlake01TranslationYAnimation.fillMode = fillMode
		snowFlake01TranslationYAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["snowFlake01"]?.layer.addAnimation(snowFlake01TranslationYAnimation, forKey:"Spinning_TranslationY")
	}

	func removeSpinningAnimation() {
		self.layer.removeAnimationForKey("Spinning")
		self.viewsByName["snowFlake"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake02"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake02"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake02"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake06"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake06"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake06"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake15"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake15"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake15"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["Ampersand SnowFlake"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake10"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake10"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake10"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake08"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake08"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake08"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake03"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake03"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake03"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake09"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake09"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake09"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake14"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake14"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake14"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake17"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake17"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake17"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake11"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake11"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake11"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake16"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake16"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake16"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["chilling"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake07"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake07"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake07"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake04"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake04"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake04"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake05"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake05"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake05"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake12"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake12"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake12"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake13"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake13"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake13"]?.layer.removeAnimationForKey("Spinning_TranslationY")
		self.viewsByName["snowFlake01"]?.layer.removeAnimationForKey("Spinning_Rotation")
		self.viewsByName["snowFlake01"]?.layer.removeAnimationForKey("Spinning_Opacity")
		self.viewsByName["snowFlake01"]?.layer.removeAnimationForKey("Spinning_TranslationY")
	}

	override func animationDidStop(anim: CAAnimation, finished flag: Bool) {
		if let completion = self.animationCompletions[anim] {
			self.animationCompletions.removeValueForKey(anim)
			completion(flag)
		}
	}

	func removeAllAnimations() {
		for subview in viewsByName.values {
			subview.layer.removeAllAnimations()
		}
		self.layer.removeAnimationForKey("Spinning")
	}
}